### ISSUE TITLE
Webpack trying to find config for shared package instead of target package

### ISSUE THREAD

**Issue by simkessy** [dan-kez/lerna-webpack-example#15]
Hi, 

I'm trying to set up a monorepo with workspaces. I have this structure: 

```
/monorepo/
    /services/
         /my-project/
                .babelrc
                package.json
                webpack.config.js
        /common/
              /src/
                  index.jsx (react component)
```

I load all this into docker using volumes then from `my-project` I run `webpack`, but i get this error: 

> Resolve error: Cannot find module /monorepo/services/common/webpack.config.js

It seems like webpack is trying to find a config file within common but I want to use the one that's in `my-project`. 

Am I suppose to create another webpack config inside common or can I reuse the config from `my-project`

**Comment by dan-kez** [comment]
Do you have an example repo at github to look at?
