### ISSUE TITLE
can we have a typescript version please?

### ISSUE THREAD

**Issue by petabytestorage** [dan-kez/lerna-webpack-example#2]

**Comment by dan-kez** [comment]
@petabytestorage Sure I could update this for TypeScript. I started transitioning packages over to TS at work (we use a very similar structure to the one shown in the repository).

What I'll do is convert the main routing package to TS as well as add one TS "Leaf". That way you can see how to have both JS & TS coexist (which is likely necessary if you have an existing lerna repository).

Let me know if you have any thoughts on this approach / if this is what your meant.

**Comment by petabytestorage** [comment]
yes that is exactly what i meant and i think that would be great!  i have been trying to modify your example and others to get that combination but so far nothing usable yet. thank you @dan-kez  if you succeed i will enjoy trying your style for my next app.

**Comment by petabytestorage** [comment]
we got our own version working but still we are interested in your version @dan-kez

**Comment by dan-kez** [comment]
Hey @petabytestorage sorry for not jumping on this. I took a holiday over the long weekend (MLK day in the states).

I likely won't be able to update this until Thursday night but I have it on my calendar to do so!

**Comment by petabytestorage** [comment]
cool i am excited to see it!  we chose `yarn` version of lerna and have `workspaces` enabled but do not know if they serve any purpose so may disable soon... i will enjoy comparing the details.

**Comment by dan-kez** [comment]
@petabytestorage I just put together a PR with the updates for TS. Let me know if you have any thoughts or questions. I'll merge it later today / this week.
