### ISSUE TITLE
Bundling

### ISSUE THREAD

**Issue by imranweb** [dan-kez/lerna-webpack-example#5]
Sorry for creating issue as I couldn't find the proper way to ask question.
I want to know how the bundle called "vendor~main.js" is getting created?

**Comment by dan-kez** [comment]
Hi @imranweb !

The `vendor~main.js` file is being created by webpack at build time. See these lines: https://github.com/dan-kez/lerna-webpack-example/blob/master/packages/router/webpack.config.js#L60-L64

For more info take a look at webpacks docs here: https://webpack.js.org/guides/code-splitting/

I'll close this issue but if you have follow up questions let me know!
